apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: influxdb-data
  namespace: influxdb-k8s
spec:  
  accessModes:  
  - ReadWriteOnce  
  resources:  
    requests:  
      storage: 2Gi